forge "https://forgeapi.puppetlabs.com"

####################### NOTE #############################
# All modules *must* be pinned to a specific version/tag #
##########################################################

# modules from the puppet forge
mod 'KyleAnderson/consul', '1.1.0'
