#!/bin/bash

# /usr/local/bin isn't set yet in our PATH
export PATH=/usr/local/bin:$PATH

USER_DATA=$(curl -fqs http://169.254.169.254/latest/user-data)
eval "$USER_DATA"

REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)

CONSUL_DC="${NUBIS_ENVIRONMENT}-${REGION}-${NUBIS_ACCOUNT}"

# If we were not told an explicit cluster size via user-data, find it via our ASG
if [ ! "$CONSUL_BOOTSTRAP_EXPECT" ]; then
  MY_INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
  ASG_NAME=$(aws autoscaling describe-auto-scaling-instances --region "$REGION" --instance "$MY_INSTANCE_ID" --query 'AutoScalingInstances[0].AutoScalingGroupName' --output text)
  if [ "$ASG_NAME" ]; then
    # Figure out what the ASG desired capacity (i.e. cluster size) is set at
    CONSUL_BOOTSTRAP_EXPECT=$(aws autoscaling describe-auto-scaling-groups --region "$REGION" --auto-scaling-group-name "$ASG_NAME" --query 'AutoScalingGroups[0].DesiredCapacity')
  fi
fi

if [ "$CONSUL_BOOTSTRAP_EXPECT" ]; then
cat <<EOF > /etc/consul/zzz-bootstrap.json
{
  "bootstrap_expect": $CONSUL_BOOTSTRAP_EXPECT
}
EOF
fi

# Grab the master ACL token from credstash (if not in user-data)
if [ ! "$CONSUL_MASTER_ACL_TOKEN" ]; then
  CONSUL_MASTER_ACL_TOKEN=$(nubis-secret get master_acl_token)
fi

if [ "$CONSUL_MASTER_ACL_TOKEN" ]; then

  # Default to allow all
  if [ -z "$CONSUL_ACL_DEFAULT_POLICY" ]; then
    CONSUL_ACL_DEFAULT_POLICY="allow"
  fi

  # default to cached (and maybe stale) ACLs
  if [ -z "$CONSUL_ACL_DOWN_POLICY" ]; then
    CONSUL_ACL_DOWN_POLICY="extend-cache"
  fi

cat <<EOF > /etc/consul/zzz-acl.json
{
  "acl_datacenter": "$CONSUL_DC",
  "acl_master_token": "$CONSUL_MASTER_ACL_TOKEN",
  "acl_default_policy": "$CONSUL_ACL_DEFAULT_POLICY",
  "acl_down_policy": "$CONSUL_ACL_DOWN_POLICY"
}
EOF

# Create the ACLs, and since we are blacklisting for now, we don't need
# to be very specific, the Platform token gets *.* since we allow by default,
# and it's the anonymous one that gets denied explicitely. Will need inverting

cat <<EOF > /etc/consul/acl.pp
consul_acl { "Nubis Platform":
  ensure => 'present',
  rules  => {},
  type   => 'client',
  acl_api_token => '$CONSUL_MASTER_ACL_TOKEN',
}

# XXX: Missing support for storage and mysql(bugzilla)
consul_acl { "Anonymous Token":
  ensure => 'present',
  rules  => {
    "key" => {
      "_rexec/" => {
        "policy" => "deny"
      },
      "environments/" => {
        "policy" => "read"
      },
      "jumphost" => {
        "policy" => "deny"
      },
      "fluent" => {
        "policy" => "deny"
      },
      "proxy" => {
        "policy" => "deny"
      },
      "nubis" => {
        "policy" => "deny"
      },
      "consul-ready" => {
        "policy" => "read"
      }
    },
    "service" => {
      "fluentd" => {
        "policy" => "read"
      },
      "proxy" => {
        "policy" => "read"
      }
    }
  },
  type   => 'client',
  acl_api_token => '$CONSUL_MASTER_ACL_TOKEN',
}
EOF
fi


# Grab the secret from credstash (if not in user-data)
if [ "$CONSUL_SECRET" ]; then
  echo "$CONSUL_SECRET" > /etc/consul/consul.secret
else
  SECRET=$(nubis-secret get secret)
  echo "$SECRET" > /etc/consul/consul.secret
fi

# Grab the cert from credstash (if not in user-data)
if [ "$CONSUL_CERT" ]; then
  echo "$CONSUL_CERT" | tr " " "\n" | perl -pe 's/--BEGIN\n/--BEGIN /g' | perl -pe 's/--END\n/--END /g' > /etc/consul/consul.pem
else
  CERT=$(nubis-secret get ssl/cert)
  echo "$CERT" > /etc/consul/consul.pem
fi

# Grab the key from credstash (if not in user-data)
if [ "$CONSUL_KEY" ]; then
  echo "$CONSUL_KEY" | tr " " "\n" | perl -pe 's/--(BEGIN|END)\n/--$1 /m' | perl -pe 's/ RSA\n/ RSA /g' | perl -pe 's/ PRIVATE\n/ PRIVATE /g' > /etc/consul/consul.key
else
  KEY=$(nubis-secret get ssl/key)
  echo "$KEY" > /etc/consul/consul.key
fi

# Ensure we don't auto-join anything, so create an auto-join skip marker
touch /etc/consul/zzz-join.skip
