#!/bin/bash

export PATH=/usr/local/bin:$PATH

eval "$(nubis-metadata)"
NUBIS_REGION=$(nubis-region)

echo "Attempting to find initial peers"
/usr/local/bin/consul-aws-join

echo "Waiting for a Consul leader, possibly forever"

LEADER=""

while [ "$LEADER" == "" ]; do 
  sleep 1;
  LEADER=$(curl -fqs http://localhost:8500/v1/status/leader | jq -r .)
done

echo "Finally, leader is '$LEADER'"

KEY_PREFIX="/arenas/$NUBIS_ARENA/global/$NUBIS_PROJECT"

# XXX: At this point, there could be a platform ACL from a previous cluster, so make sure
if [ -r /etc/consul/zzz-acl.json ]; then
    MASTER_ACL_TOKEN=$(jq -r .acl_master_token < /etc/consul/zzz-acl.json)
else
    MASTER_ACL_TOKEN="anonymous"
fi

/usr/local/bin/consul-get-or-set "$MASTER_ACL_TOKEN" "$KEY_PREFIX/cert"   "cat /etc/consul/consul.pem"
/usr/local/bin/consul-get-or-set "$MASTER_ACL_TOKEN" "$KEY_PREFIX/key"    "cat /etc/consul/consul.key"
/usr/local/bin/consul-get-or-set "$MASTER_ACL_TOKEN" "$KEY_PREFIX/secret" "cat /etc/consul/zzz-tls.json | jq -r .encrypt"

# Perform global post-boostrap operations, with exclusive lock
/usr/local/bin/consul lock "consul-$NUBIS_ARENA-post-bootstrap" /usr/local/bin/consul-post-bootstrap

# Register our ASG membership in DNS
/usr/local/bin/consul-dns-update
