#!/bin/bash

### WE ARE INVOKED WITH AN EXCLUSIVE LOCK ###

export PATH=/usr/local/bin:$PATH

eval "$(nubis-metadata)"

# Run puppet manifests dropped in /etc/consul for post-boostrap configuration (ACLs)
for PUPPET_FILE in /etc/consul/*pp; do
  puppet apply "$PUPPET_FILE"
done

# XXX: At this point, there should be a platform ACL if we wanted one
if [ -r /etc/consul/zzz-acl.json ]; then
    MASTER_ACL_TOKEN=$(jq -r .acl_master_token < /etc/consul/zzz-acl.json)
fi

# Find out what the platform ACL is
PLATFORM_ACL=$(curl -fqs "http://localhost:8500/v1/acl/list?token=$MASTER_ACL_TOKEN" | jq -r '.[] | select(.Name=="Nubis Platform").ID')
if [ "$PLATFORM_ACL" != "" ]; then
    REGION=$(nubis-region)
    CURRENT_PLATFORM_ACL=$(unicreds --region "$REGION" get "nubis/$NUBIS_ARENA/consul/acl_token" -E "region:$REGION" -E "arena:$NUBIS_ARENA" -E "service:nubis")
    if [ "$CURRENT_PLATFORM_ACL" != "$PLATFORM_ACL" ]; then
      # Store current platform ACL in credstash for others to retrieve
      unicreds --region "$REGION" put "nubis/$NUBIS_ARENA/consul/acl_token" "$PLATFORM_ACL" -E "region:$REGION" -E "arena:$NUBIS_ARENA" -E "service:nubis"
    fi
fi

# Finalize by creating a well-known KV
consulate --token="$MASTER_ACL_TOKEN" kv set consul-ready "$(date '+%s')"
