#!/bin/bash

### WE ARE INVOKED WITH AN EXCLUSIVE LOCK ###

export PATH=/usr/local/bin:$PATH

USER_DATA=$(curl -fqs http://169.254.169.254/latest/user-data)
eval "$USER_DATA"

# Run puppet manifests dropped in /etc/consul for post-boostrap configuration (ACLs)
for PUPPET_FILE in /etc/consul/*pp; do
  puppet apply "$PUPPET_FILE"
done

# XXX: At this point, there should be a platform ACL if we wanted one
if [ -r /etc/consul/zzz-acl.json ]; then
    MASTER_ACL_TOKEN=$(jq -r .acl_master_token < /etc/consul/zzz-acl.json)
fi

# Find out what the platform ACL is
PLATFORM_ACL=$(curl -fqs "http://localhost:8500/v1/acl/list?token=$MASTER_ACL_TOKEN" | jq -r '.[] | select(.Name=="Nubis Platform").ID')
if [ "$PLATFORM_ACL" != "" ]; then
    REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r)
    CURRENT_PLATFORM_ACL=$(credstash --region "$REGION" get "nubis/$NUBIS_ENVIRONMENT/consul/acl_token" "region=$REGION" "environment=$NUBIS_ENVIRONMENT" "service=nubis")
    if [ "$CURRENT_PLATFORM_ACL" != "$PLATFORM_ACL" ]; then
      # Store current platform ACL in credstash for others to retrieve
      credstash --region "$REGION" put -a "nubis/$NUBIS_ENVIRONMENT/consul/acl_token" "$PLATFORM_ACL" "region=$REGION" "environment=$NUBIS_ENVIRONMENT" "service=nubis"
    fi
fi

# XXX: Need an agnostic way to do this

# Datadog

DATADOG_API_KEY_PATH="environments/$NUBIS_ENVIRONMENT/global/datadog/config/api_key"
DATADOG_API_KEY=$(nubis-secret get datadog/api_key)
CONSUL_DATADOG_API_KEY=$(consulate kv get "$DATADOG_API_KEY_PATH")

if [ "$DATADOG_API_KEY" != "$CONSUL_DATADOG_API_KEY" ]; then
  echo "Injecting Datadog API key"
  consulate --token="$MASTER_ACL_TOKEN" kv set "$DATADOG_API_KEY_PATH" "$DATADOG_API_KEY"
fi

# Finalize by creating a well-known KV
consulate --token="$MASTER_ACL_TOKEN" kv set consul-ready "$(date '+%s')"
