#!/bin/sh

# This is an auto-bootstraper for consul

eval `ec2metadata --user-data`

cat <<EOF | tee /etc/consul/zzz-autogenerated.json
{
  "bootstrap_expect": $CONSUL_BOOTSTRAP_EXPECT,
  "token": "$CONSUL_TOKEN",
  "datacenter": "$CONSUL_DC"
}
EOF

#XXX: Wish there was a way to self-discover members of our autoscaling group...
if [ "$CONSUL_JOIN" ]; then
cat <<EOF | tee /etc/consul/zzz-autojoin.json
{
  "start_join": [ "$CONSUL_JOIN" ]
}
EOF
fi

service consul restart

exit 0